language: ruby
cache: bundler

before_install: gem update --system && gem install bundler

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2.7
  - jruby-9.1.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

addons:
  code_climate:
    repo_token: 97a54878f464b101386de95de0863407520593d817bbaa8e6f851cdb70d30e97