language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - 2.0.0
  - 1.9.3
  - jruby-9.1.2.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

addons:
  code_climate:
    repo_token: 97a54878f464b101386de95de0863407520593d817bbaa8e6f851cdb70d30e97